openapi: "3.0.3"
info:
  title: "Ktorplate APIs"
  description: "All APIs from Ktorplate in a single place"
  version: "1.0.0"

servers:
  - url: "http://0.0.0.0:8080"
paths:
  /signup:
    post:
      summary: Creates a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '201':
          description: User created
  /login:
    post:
      summary: Authenticates an user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authentication succeeded
  /users:
    get:
      summary: Get a list of all users
      responses:
        '200':
          description: Users list
  /users/{email}:
    get:
      summary: Get an user by its email
      parameters:
        - in: path
          name: email
          required: true
          description: User's email address
          schema:
            type: string
      responses:
        '200':
          description: User found
        '404':
          description: User not found
  /health:
    get:
      summary: Health API
      responses:
        '200':
          description: OK

components:
  schemas:
    SignUpRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string